### PR TITLE
Add adsb json decoding

### PR DESCRIPTION
**Pull request by fredclausen**

### CODE REVIEW

**Comment by jcdeimos** [comment]
I think before this gets close to landing, will want to look at restructuring slightly.

Thinking something along the lines of:

```
src
- message_types:
- - acars.rs
- - adsb_beast.rs
- - adsb_json.rs
- - vdlm2.rs
- error_handling:
- - errors.rs
```

Also would suggest spending some time looking into how to implement `From<>`:

```
use serde_json::Error

impl From<Error> for DeserializatonError {
    fn from(value: Error) -> Self {
        DeserializatonError::SerdeError(value)
    }
}
```

This would allow you to take a serde_json error and simply use `.into()` instead of having to specify the Enum each time.

**Comment by fredclausen** [comment]
Makes sense and I'll do that this morning. I did something similar for the Error handling, but I just created an `enum` of the possible error types and mapped the error type to the enum. Now that I see your suggestion I realize how much better that is.

**Comment by fredclausen** [comment]
I was also considering that likely the user of this library would not necessarily want to decode all types of known messages, and simply a subset of them. It would be cool to use the "features" thing to conditionally add in the decoder types. I am not going to mess about with that right now, but it's on my list of things to do.

**Comment by fredclausen** [comment]
Sorry for the novel, but...

* Deserializes ADSB Raw frames in a way that I think makes sense
* Added in ADSB Raw tests
* Renamed `tests/acarsvdlm2message_tests.rs` to `tests/DecoderAllTests.rs`

This is ready for someone else's eyes to look at. I need to split out the `adsb_raw` file into more manageable chunks, but that shouldn't affect the much I wouldn't think. I really want to add in ADSB Beast decoding but this isn't the right time for it. Cleaning up everything and reorganizing things in a way that makes sense is what needs to happen before I go in to that.

I think I have all of the tests working, and I think it's deserializing adsb raw frames.

I left a few `FIXME/TODOs` in there because my brain couldn't wrap around what the issue actually is. Specifically the `format_adsb_raw_frames_from_bytes` helper function I wrote. There is a round-robin thing I had to do to convert a `Vec<u8>` of the input bytes in to a string, and then BACK to a `Vec<u8>` to make it all work. Obviously, that's a terrible solution, but I just couldn't get it to work any other way. I suspect the issue is my lack of understanding of the relationship of bits/bytes and what deku really wants.

Additionally, I'm not really satisfied with how the test suite works on the u8 side of things. It's basically all hard coded to assume the u8 input is ADSB raw frames, but that won't hold true once I add in ADSB beast. Maybe the answer is to re-encode the test files to be just strings of the hex values of the ADSB Raw (and eventually beast) frames and go from there?

Related to above, the enums `TestFileType` and `FileTypes` in `mod.rs` just seem messy and confusing. I used those to keep track of the different file types/data structures but I feel like I've done that bit wrong, but I can't figure a better way of doing things.

The test suite is basically impossibly slow now running the speed tests because of the massive increase of messages. On my machine the second speed test has 21,315,000 messages and uses not a lot of CPU; I suspect it's a RAM issue and it's page swapping or whatever it's called. Probably best to pair the duplication down?

**Comment by fredclausen** [comment]
Additional thought:

I know you mentioned Generics and wrapping all of the decoded outputs in that; at least, that's how I understood it. I think that's a necessary step, but one I'm not entirely sure how to proceed with. I don't know if that should be part of this PR. This one is fairly massive (I'm sorry, I know that is poor form...) and it may be worth not doing it for this PR, but taking the time after this is merged and before ADSB Beast.

**Comment by fredclausen** [comment]
After much thought, and trying to make this make sense, I'm not sure it makes any sense at all to merge ADSB and ACARS data in one library.

I'll go ahead and close this.

**Pull request closed without merging**
